#ifndef __SEATS_TYPES_HPP__
#define __SEATS_TYPES_HPP__

#define leave_if_true(x) if((x)) return
#define ATTESTATION_CLIENT_HELLO_EXTENSION_TYPE 65282
#define ATTESTATION_CERTIFICATE_EXTENSION_TYPE 65280
#define SEATS_CERT_FILE_PATH "/dev/shm/cert.pem"
#define SEATS_KEY_FILE_PATH "/dev/shm/key.pem"

namespace seats{

enum seats_status{
	OK = 0,

    // SOCKET RELATED ERRORS
    UNABLE_TO_CREATE_SOCKET,
    UNABLE_TO_BIND_SOCKET,
    UNABLE_TO_LISTEN,
    UNABLE_TO_SOCKET_REUSE_ADR,
    UNABLE_TO_ACCEPT_CONNECTION,

    // SSL CONTEXT RELATED ERRORS
    UNABLE_TO_CREATE_SSL_CONTEXT,
    FAILED_TO_ADD_SSL_EXTENSIONS,
    UNABLE_TO_CONFIGURE_SSL_CONTEXT,

    // CERTIFICATE GENERATION RELATED ERRORS
    UNABLE_TO_GENERATE_PRIVATE_KEY,
    UNABLE_TO_CREATE_X509,
    FAILED_TO_SET_SERIAL_NUMBER,
    FAILED_TO_SET_X509_BEGIN,
    FAILED_TO_SET_X509_END,
    FAILED_TO_SET_X509_PUBKEY,
    FAILED_TO_GET_X509_NAME,
    FAILED_TO_SET_X509_NAME_1,
    FAILED_TO_SET_X509_NAME_2,
    FAILED_TO_SET_X509_NAME_3,
    FAILED_TO_SET_X509_NAME_4,
    FAILED_TO_SIGN_X509,
        
    // SSL SESSION RELATED ERRORS
    UNABLE_TO_CREATE_SSL_SESSION,
    UNABLE_TO_SET_SOCKET_FOR_SSL_SESSION,
    UNABLE_TO_ACCEPT_SESSION,
    FAILED_VERIFICATION,

	CONNECTION_ERROR,
    RECEIVING_FAILED,
	ATTESTATION_INVALID,
	SENDING_FAILED, 
    NOT_IMPLEMENTED_ERROR
};

}
#endif // !__SEATS_TYPES_HPP__
